### ISSUE TITLE
Error while receiving deployment event from Marathon

### ISSUE THREAD

**Issue by harnash** [allegro/marathon-consul#33]
After registering to an event bus in Marathon I get the following error:
```javascript
{"EventType":"deployment_success","level":"debug","msg":"Received event","time":"2016-01-25T14:18:50Z"}
{"error":"Cannot handle deployment_success","level":"debug","msg":"Returning 400 due to malformed request","time":"2016-01-25T14:18:50Z"}
```

We are running Marathon: 0.13.0

**Comment by dankraw** [comment]
Hi, `deployment_success` event is not handled by marathon-consul - we respond with status code 400 ("Returning 400 due to malformed request") to events we don't handle. It's a bit misleading and should be changed in the future. As of now, please don't worry about that. ;)
If you want to see less output, you can change the logging level to `info` with `--log-level: info`.

**Comment by harnash** [comment]
OK. Thanks for clarification.
