### ISSUE TITLE
Allow tasks to register without health checks

### ISSUE THREAD

**Issue by moderation** [allegro/marathon-consul#51]
A Consul service definition does not have to have a healthcheck - https://www.consul.io/docs/agent/services.html

`A service definition must include a name and *may optionally* provide an id, tags, address, port, check, and enableTagOverride.` (emphasis mine)

I'm interested in using marathon-consul in a RPC context where availability and health checks are looked after at the RPC layer and all I need is a relatively up to date list of my Marathon task endpoints.

In my testing, if a task doesn't have a health check but is labeled correctly, it won't show up in Consul.

Could this behavior be changed to allow for tasks / services without health checks?

**Comment by janisz** [comment]
Hi @moderation 

We decided to register only tasks with healthcheck on purpose. When application is deployed we wait until task becomes healthy and then register it in consul. At the beginning it was easier to handle task health changed event  than deployment success. Als allows us to register tasks faster then at the end of deployment. Currently only HTTP checks are supported but TCP checks are available in both  Marathon and Consul and could be a solution for you (checking if application is accepting connections). Will TCP healthchecks solve your problem?

**Comment by dankraw** [comment]
@moderation 
Speaking about the current marathon-consul release, in order to register a service in Consul you have to:
* specify at least one healthcheck with your Marathon task - actually, the check **can be of any type** (HTTP, TCP, Command),
* if there are more healthchecks specified, all of them have to go green, so we know the task is healthy.

We pass only a single HTTP healthcheck to Consul (TCP checks should be added in the future), so - for example - if you have a TCP/Command check specified, you will have a service registered in Consul anyway, though with a Serf (Agent node) healthcheck registered only. 
It is not a documented feature, but should work. I hope this will help you somehow - tell us if it did. 

As @janisz explained, registering tasks not having any healthchecks specified would force us to handle different event types and could be quite troublesome.

**Comment by moderation** [comment]
@janisz and @dankraw thanks for the explanation and rationale. I might be able to add some simple health checks to allow for registration in Consul. In a tightly controlled and locked down environment where security is a premium, opening ports to health checks may not be an option. My use case is a bit different and towards an RPC system that handles the health checks at that layer and I understand that is an edge case.  Thanks again.

**Comment by dankraw** [comment]
@moderation If you don't plan to set any "real" checks, you may try a "fake" one of `command` type, like `pwd`. This will make your tasks healthy immediately and registered in Consul.
