### ISSUE TITLE
Event based notification

### ISSUE THREAD

**Issue by jogster** [allegro/marathon-consul#74]
Hi All,
 I was under the impression that this version of marathon-consul was event based. As it was the ciscocloud version was based on polling.

I am a bit confused as I have to use two flags (--sync-interval=30s --sync-force=true) to actually get it to recognise that services are registering/deregistering. In reality I want to have a 1s value but I am unsure if this is correct...

I cannot see any difference (in functionality) with the old ciscocloud version.

Any advice for me?

**Comment by janisz** [comment]
Hi @jogster 

allegro/marathon-consul is event based (CiscoCloud/marathon-consul is event based too, while CiscoCloud/mesos-consul is based on polling, see [differences](https://github.com/allegro/marathon-consul#differences)).

I think idea of sync needs some clarification. Whenever marathon publishes event about task started/stopped, marathon-consul register/deregister this task in consul. We run sync periodically to make sure all tasks running on marathon are registered in consul and there is no dead task registered. The difference could exist because there could be communication error between marathon-consul and consul (network partition, dead consul agent) or marathon (event was not received). 
`--sync-interval` define how often sync will happen and `--sync-force=true` force sync on every instance (by default only instance that is running on same host as marathon leader will perform sync).

Recommended setup for marathon-consul is to run it on same hosts as marathon, to minimize network traffic. In this setup we are using 15 min sync interval.

**Comment by dankraw** [comment]
Hi @jogster 
Have you configured Marathon's event bus callback for your marathon-consul instance? 
https://github.com/allegro/marathon-consul#setting-up-marathon-consul-after-installation
This will make your services (de)registered immediately.

**Comment by jogster** [comment]
Just added marthon-cosul as an event listener works great now -- I read about callbacks but did not appreciated the importance of it. My bad...
