### ISSUE TITLE
Synchro vs events processing race / synchro cache invalidation

### ISSUE THREAD

**Issue by dankraw** [allegro/marathon-consul#88]
There is a possibility that during the time the scheduled synchro takes place, 
an event from Marathon (like TASK_KILLED) is received and processed (causing service deregistration), but the synchro later on overrides it effect (service registration again). We end up with a service that should not be registered any more.

This is caused because synchro creates a local cache of Marathon apps and Consul services at the beginning of the process, and uses it to apply a diff result to Consul. This diff may already be stale if the synchro takes some time.

**Comment by dankraw** [comment]
The question is if and how it should be fixed?

**Comment by janisz** [comment]
Possible solution is to "stop the world" during synchronization. This means when synchronisation starts all events are queued and processed after synchronisation ends.

**Comment by janisz** [comment]
Another solution that comes to my mind is to reduce stop the world time for application. Currently, sync downloads all marathon apps with tasks and compare them with consul services. We can get services list from consul and then for each service check it's app in marathon. Instead of making one expensive call to marathon and downloading megabytes of data we will make fast and small sequential calls. Whole sync procedure will take longer but period between obtaining data from marathon and comparing them with consul will be more or less the same for every application. This means time frame in which we have race will be smaller. Currently applications from the end of the list will be work on stale data since sync takes minutes.

@adamdubiel What do you think?

**Comment by adamdubiel** [comment]
I agree with fetching granular changes:

* fetch list of apps from Consul
* for each compare state
* do we need to fetch list of apps from Marathon as well? in case it is not in Consul, but is in Marathon

However we only make the window smaller. We have this bug because current implementation of sync and event receiver have nothing in common - they just send requests to Consul. What if sync was actually publishing events onto the queue and contradicting events that happened in some time window (like 100ms) would get merged? We would need some precedence logic.

However this is bit complicated, so for now making the window smaller would probably help us get rid of this bug for 99.999. Even with current, slow implementation we only saw this happening twice or thrice.
