### ISSUE TITLE
Revert marathon tag label semantics

### ISSUE THREAD

**Issue by vervas** [allegro/marathon-consul#91]
With the current implementation, tags that need to be passed to consul are filtered by their value. this feels slightly odd and I was wondering whether having a labels called `consul_tags` that includes an array of strings would make more sense.

Would altering https://github.com/allegro/marathon-consul/blob/master/consul/consul.go#L268
and https://github.com/allegro/marathon-consul/blob/master/apps/app.go#L32 be enough for this or would it require more substantial changes?

**Comment by janisz** [comment]
When we developed this feature we have thought about solution with one label. For first sight it looks natural to take one label and parse it's value. But we will lose some functionality with this approach. In our ecosystem we have some common tags that are shred by services with certain. With separated label we can easy filter them with Marathon API or in UI. Maybe the least but noticeable feature of keeping one tag per label is how marathon UI presents labels and definitely it looks better with multiple short labels than one long label.

I think we can add support for both methods of defining labels to keep backward compatibility. As you say changes are required only in [consul.marathonLabelsToConsulTags()](https://github.com/allegro/marathon-consul/blob/69c638ecd9603d835e962fc32c9240480575b498/consul/consul.go#L268) and is quite simple because require to add entries from `labels['consul_tags']`, something like this should work:

    tags = append(tags, strings.Split(labels["consul_tag"], ",")...)

Also adding some tests and docs will be required.

**Comment by vervas** [comment]
Thanks for the feedback. I'll have a look and give it a try.

Indeed from a UI point of view it looks better having multiple ones, but as said adding the semantic on the value instead of the key felt a bit cumbersome. My main misconception was that a marathon label can take an array of strings instead of just a (comma separated) string, which then justifies your design decision.

I will close this for now and maybe come back with a PR about it.
